export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_POSTS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE'
export const USER_CHATS_STATE_CHANGE = 'USER_CHATS_STATE_CHANGE'
export const USER_NOTIFICATIONS_STATE_CHANGE = 'USER_NOTIFICATIONS_STATE_CHANGE'

export const USER_SEARCH_KEYS_STATE_CHANGE = 'USER_SEARCH_KEYS_STATE_CHANGE'
export const USER_SEARCH_KEYS_DELETE = 'USER_SEARCH_KEYS_DELETE'
export const USER_SEARCH_SIMPLES_CHANGE = 'USER_SEARCH_SIMPLES_CHANGE'
export const USER_SEARCH_DETAILS_CHANGE = 'USER_SEARCH_DETAILS_CHANGE'
export const USER_SEARCH_INPUT_CHANGE = 'USER_SEARCH_INPUT_CHANGE'

export const USER_CHAT_STATE_CHANGE = 'USER_CHAT_STATE_CHANGE'
export const USER_FOLLOWINGS_STATE_CHANGE = 'USER_FOLLOWINGS_STATE_CHANGE'
export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE'
export const USER_UNREAD_MSG_CNT_CHANGE = 'USER_UNREAD_MSG_CNT_CHANGE'
export const USER_UNREAD_NOTIFY_CNT_CHANGE = 'USER_UNREAD_NOTIFY_CNT_CHANGE'

export const USER_LOGOUT = 'USER_LOGOUT'
export const USERS_STATE_CHANGE = 'USERS_STATE_CHANGE'
export const USERS_ADD_CHANGE = 'USERS_ADD_CHANGE'
export const USERS_POSTS_ADD_CHANGE = 'USERS_POSTS_ADD_CHANGE'


export const LIVE_POST_CHANGE = 'LIVE_POST_CHANGE'
export const LIVE_MESSAGE_CHANGE = 'LIVE_MESSAGE_CHANGE'
export const LIVE_NOTIFICATION_CHANGE = 'LIVE_NOTIFICATION_CHANGE'



export const USERS_POSTS_STATE_CHANGE = 'USERS_POSTS_STATE_CHANGE'
export const USERS_POST_LIKE_STATE_CHANGE = 'USERS_POST_LIKE_STATE_CHANGE'
export const USERS_POST_COMMENT_STATE_CHANGE = 'USERS_POST_COMMENT_STATE_CHANGE'
export const USERS_POST_ATTR_STATE_CHANGE = 'USERS_POST_ATTR_STATE_CHANGE'

export const CREATE = 'CREATE';
export const UPDATE = 'UPDATE';
export const DELETE = 'DELETE';
export const FETCH_ALL = 'FETCH_ALL';
export const FETCH_POST = 'FETCH_POST';
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH';
export const COMMENT = 'COMMENT';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';

export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING'
